CREATE TABLE IF NOT EXISTS channels (
  'id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  'name' TEXT,
  'topic' TEXT,
  'timestamp' INTEGER NOT NULL,
  'deleted' TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
  'id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  'channelId' INTEGER NOT NULL,
  'authorId' INTEGER NOT NULL,
  'content' TEXT,
  'timestamp' INTEGER NOT NULL,
  'deleted' TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  'id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  'login' TEXT NOT NULL UNIQUE,
  'joinTimestamp' INTEGER NOT NULL,
  'password' TEXT NOT NULL,
  'token' TEXT,
  'name' TEXT NOT NULL,
  'status' TEXT NOT NULL,
  'iconURL' TEXT,
  'deleted' TEXT NOT NULL
);

CREATE TABLE signupTokens (
  'tokenId' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  'token' TEXT NOT NULL,
  'tokenExpirationTimestamp' INTEGER NOT NULL
);
